# docker-compose.yaml for regression testing
# spins up a container with the current development version of the backend
# and a container with the current test version (build from the current branch or working copy) of the backend
services:
  edirom-online-backend-development:
    container_name: eol-dev
    image: edirom/edirom-online-backend:develop
    ports:
      - "8090:8080"
  edirom-online-backend-test:
    container_name: eol-test
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
